apiVersion: v1
kind: Service
metadata:
  name: csm-service
spec:
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: csm-port
      protocol: TCP
  selector:
    app: csmmigration
  type: NodePort